### ISSUE TITLE
Failed to establish a new connection: [Errno 61] Connection refused

### ISSUE THREAD

**Issue by usagiryu** [codezjx/netease-cloud-music-dl#1]
ncm -p https://music.163.com/#/playlist?id=575568611
1 song name:静かな冬の夜
Traceback (most recent call last):
  File "/usr/local/bin/ncm", line 11, in <module>
    load_entry_point('netease-cloud-music-dl==0.2.0', 'console_scripts', 'ncm')()
  File "/usr/local/lib/python3.6/site-packages/netease_cloud_music_dl-0.2.0-py3.6.egg/ncm/start.py", line 75, in main
  File "/usr/local/lib/python3.6/site-packages/netease_cloud_music_dl-0.2.0-py3.6.egg/ncm/start.py", line 41, in download_playlist_songs
  File "/usr/local/lib/python3.6/site-packages/netease_cloud_music_dl-0.2.0-py3.6.egg/ncm/downloader.py", line 47, in download_song_by_song
  File "/usr/local/lib/python3.6/site-packages/netease_cloud_music_dl-0.2.0-py3.6.egg/ncm/api.py", line 72, in get_song_url
  File "/usr/local/lib/python3.6/site-packages/netease_cloud_music_dl-0.2.0-py3.6.egg/ncm/api.py", line 35, in post_request
  File "/usr/local/lib/python3.6/site-packages/requests-2.18.3-py3.6.egg/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by conglovely** [comment]
Installed d:\program files\python\python35\lib\site-packages\netease_cloud_music
_dl-0.2.0-py3.5.egg
Processing dependencies for netease-cloud-music-dl==0.2.0
Searching for pycrypto>=2.6.1
Reading https://pypi.python.org/simple/pycrypto/
Best match: pycrypto 2.6.1
Downloading https://pypi.python.org/packages/60/db/645aa9af249f059cc3a368b118de3
3889219e0362141e75d4eaf6f80f163/pycrypto-2.6.1.tar.gz#md5=55a61a054aa66812daf516
1a0d5d7eda
error: The read operation timed out

**Comment by codezjx** [comment]
@HelloW0r1d 兔子哥，试了一下你给的歌单https://music.163.com/#/playlist?id=575568611
然而并不能复现哇，根据log信息判断应该是在解析url的json的时候遇到了问题。

单独试了那首歌，也木有出现问题啊，是不是你插入的姿势不对？再试一次看看，我都开始怀疑人生了~
> ncm -s https://music.163.com/#/song?id=27594402

返回歌曲url的json如下：
```json
{
    "data": [
        {
            "id": 27594402,
            "url": "http://m10.music.126.net/20170810002452/ac0c2635ace9893a96b335b0da31fb44/ymusic/705d/56c2/b3c7/11447417fa56216b8318d99491b786bf.mp3",
            "br": 320000,
            "size": 8263440,
            "md5": "11447417fa56216b8318d99491b786bf",
            "code": 200,
            "expi": 1200,
            "type": "mp3",
            "gain": 2.1503,
            "fee": 0,
            "uf": null,
            "payed": 0,
            "flag": 0,
            "canExtend": false
        }
    ],
    "code": 200
}
```

**Comment by usagiryu** [comment]
吼，我再试试，谢谢dalao

**Comment by usagiryu** [comment]
将python3.6卸载并安装python3.5
`ncm -p https://music.163.com/#/playlist?id=575568611
Traceback (most recent call last):
  File "/usr/local/bin/ncm", line 11, in <module>
    load_entry_point('netease-cloud-music-dl==0.2.0', 'console_scripts', 'ncm')()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/netease_cloud_music_dl-0.2.0-py3.5.egg/ncm/start.py", line 75, in main
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/netease_cloud_music_dl-0.2.0-py3.5.egg/ncm/start.py", line 36, in download_playlist_songs
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/netease_cloud_music_dl-0.2.0-py3.5.egg/ncm/api.py", line 93, in get_playlist_songs
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/netease_cloud_music_dl-0.2.0-py3.5.egg/ncm/api.py", line 25, in get_request
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests-2.18.3-py3.5.egg/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`
依旧报错
躺

**Comment by usagiryu** [comment]
将系统的默认python切换为python3 重新拉取代码并重试
第一次
Tuzis-MacBook:netease-cloud-music-dl tuzi$  ncm -p https://music.163.com/#/playlist?id=575568611
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/ncm", line 9, in <module>
    load_entry_point('netease-cloud-music-dl==0.2.0', 'console_scripts', 'ncm')()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/netease_cloud_music_dl-0.2.0-py3.5.egg/ncm/start.py", line 75, in main
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/netease_cloud_music_dl-0.2.0-py3.5.egg/ncm/start.py", line 36, in download_playlist_songs
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/netease_cloud_music_dl-0.2.0-py3.5.egg/ncm/api.py", line 93, in get_playlist_songs
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/netease_cloud_music_dl-0.2.0-py3.5.egg/ncm/api.py", line 25, in get_request
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests-2.18.3-py3.5.egg/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Json解析出错

Tuzis-MacBook:netease-cloud-music-dl tuzi$  ncm -p https://music.163.com/#/playlist?id=575568611
1 song name:月がきれい
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/ncm", line 9, in <module>
    load_entry_point('netease-cloud-music-dl==0.2.0', 'console_scripts', 'ncm')()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/netease_cloud_music_dl-0.2.0-py3.5.egg/ncm/start.py", line 75, in main
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/netease_cloud_music_dl-0.2.0-py3.5.egg/ncm/start.py", line 41, in download_playlist_songs
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/netease_cloud_music_dl-0.2.0-py3.5.egg/ncm/downloader.py", line 48, in download_song_by_song
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/netease_cloud_music_dl-0.2.0-py3.5.egg/ncm/api.py", line 72, in get_song_url
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/netease_cloud_music_dl-0.2.0-py3.5.egg/ncm/api.py", line 35, in post_request
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests-2.18.3-py3.5.egg/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
第二次依旧出错

Tuzis-MacBook:netease-cloud-music-dl tuzi$  ncm -p https://music.163.com/#/playlist?id=575568611
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/ncm", line 9, in <module>
    load_entry_point('netease-cloud-music-dl==0.2.0', 'console_scripts', 'ncm')()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/netease_cloud_music_dl-0.2.0-py3.5.egg/ncm/start.py", line 75, in main
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/netease_cloud_music_dl-0.2.0-py3.5.egg/ncm/start.py", line 36, in download_playlist_songs
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/netease_cloud_music_dl-0.2.0-py3.5.egg/ncm/api.py", line 93, in get_playlist_songs
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/netease_cloud_music_dl-0.2.0-py3.5.egg/ncm/api.py", line 25, in get_request
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests-2.18.3-py3.5.egg/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
第三次依旧出错

Tuzis-MacBook:netease-cloud-music-dl tuzi$  ncm -p https://music.163.com/#/playlist?id=575568611
1 song name:月がきれい
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3-1.22-py3.5.egg/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3-1.22-py3.5.egg/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3-1.22-py3.5.egg/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3-1.22-py3.5.egg/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3-1.22-py3.5.egg/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 911, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 854, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3-1.22-py3.5.egg/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3-1.22-py3.5.egg/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x10474d198>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests-2.18.3-py3.5.egg/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3-1.22-py3.5.egg/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3-1.22-py3.5.egg/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='m10.music.126.net', port=80): Max retries exceeded with url: /20170817080939/d4fe4b7ad229a91998d6ffcb95ab483e/ymusic/1cd4/7c85/531b/a850933e77783f0d4f06cf878a6ba08d.mp3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10474d198>: Failed to establish a new connection: [Errno 61] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/ncm", line 9, in <module>
    load_entry_point('netease-cloud-music-dl==0.2.0', 'console_scripts', 'ncm')()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/netease_cloud_music_dl-0.2.0-py3.5.egg/ncm/start.py", line 75, in main
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/netease_cloud_music_dl-0.2.0-py3.5.egg/ncm/start.py", line 41, in download_playlist_songs
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/netease_cloud_music_dl-0.2.0-py3.5.egg/ncm/downloader.py", line 52, in download_song_by_song
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/netease_cloud_music_dl-0.2.0-py3.5.egg/ncm/downloader.py", line 77, in download_file
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests-2.18.3-py3.5.egg/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests-2.18.3-py3.5.egg/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests-2.18.3-py3.5.egg/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests-2.18.3-py3.5.egg/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests-2.18.3-py3.5.egg/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='m10.music.126.net', port=80): Max retries exceeded with url: /20170817080939/d4fe4b7ad229a91998d6ffcb95ab483e/ymusic/1cd4/7c85/531b/a850933e77783f0d4f06cf878a6ba08d.mp3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10474d198>: Failed to establish a new connection: [Errno 61] Connection refused',))
# 第四次出现了转机，我大概看了是 Connection Refused？

**Comment by usagiryu** [comment]
我大概找到问题了
由于使用了unblockyouku的dns
因为没有备案
<img width="778" alt="2017-08-17 1 18 24" src="https://user-images.githubusercontent.com/17731805/29391911-98e11894-834e-11e7-88be-8b0981d55fcf.png">
# 但是现在又出现了新的问题
我搭建了一个反向代理
然后发现了这个新的问题
## json返回正常
<img width="1440" alt="2017-08-17 1 20 55" src="https://user-images.githubusercontent.com/17731805/29391993-0abe85aa-834f-11e7-9218-10f652256854.png">
<img width="1440" alt="2017-08-17 1 21 02" src="https://user-images.githubusercontent.com/17731805/29392011-3397e23c-834f-11e7-8b6b-38515edcbc65.png">

log
ncm -p https://music.163.com/#/playlist?id=575568611
1 song name:月がきれい
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3/connectionpool.py", line 356, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 911, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 854, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x1053294a8>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3/connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='m10.music.126.net', port=80): Max retries exceeded with url: /20170817091435/c687b863752f0b7af38d4f347b24da65/ymusic/1cd4/7c85/531b/a850933e77783f0d4f06cf878a6ba08d.mp3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1053294a8>: Failed to establish a new connection: [Errno 61] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/ncm", line 9, in <module>
    load_entry_point('netease-cloud-music-dl==0.2.0', 'console_scripts', 'ncm')()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/netease_cloud_music_dl-0.2.0-py3.5.egg/ncm/start.py", line 75, in main
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/netease_cloud_music_dl-0.2.0-py3.5.egg/ncm/start.py", line 41, in download_playlist_songs
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/netease_cloud_music_dl-0.2.0-py3.5.egg/ncm/downloader.py", line 52, in download_song_by_song
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/netease_cloud_music_dl-0.2.0-py3.5.egg/ncm/downloader.py", line 77, in download_file
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/sessions.py", line 513, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/sessions.py", line 623, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/adapters.py", line 504, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='m10.music.126.net', port=80): Max retries exceeded with url: /20170817091435/c687b863752f0b7af38d4f347b24da65/ymusic/1cd4/7c85/531b/a850933e77783f0d4f06cf878a6ba08d.mp3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1053294a8>: Failed to establish a new connection: [Errno 61] Connection refused',))

**Comment by usagiryu** [comment]
海外ip的锅
已经解决
谢谢
幸苦了

**Comment by codezjx** [comment]
@tuzi-moe 还在怀疑是不是开了VPN~  Anyway, 解决了就好...  (￣▽￣)~*
