### ISSUE TITLE
关于 pycrypto

### ISSUE THREAD

**Issue by mengmo** [codezjx/netease-cloud-music-dl#14]
[pycrypto](https://github.com/dlitz/pycrypto) 的最新 stable 2.6.1 发布于 [2013-10-15](https://github.com/dlitz/pycrypto/releases)/[2014-06-20](https://pypi.python.org/pypi/pycrypto)，最后的 commit 时间是 2014-06-21
看起来作者已经放弃了这个项目 https://github.com/dlitz/pycrypto/issues/238
是否考虑如 https://github.com/dlitz/pycrypto/issues/238 推荐的，替换成 [pycryptodome](https://github.com/Legrandin/pycryptodome)

**Comment by yimiaodaren** [comment]
windows上安装pycryto都是难题～

**Comment by chenjunyu19** [comment]
@codezjx 现在 Arch Linux 已经将 `python-crypto` 软件包从库中移除，转而用 `python-pycryptodome` 代替。

```sh
$ sudo pacman -Syu
:: 正在同步软件包数据库...
 core 已经是最新版本
 extra 已经是最新版本
 community 已经是最新版本
 multilib 已经是最新版本
 archlinuxcn 已经是最新版本
:: 正在进行全面系统更新...
:: 替换 python-crypto 吗 (使用 community/python-pycryptodome )？ [Y/n] 
正在解决依赖关系...
正在查找软件包冲突...
错误：无法准备事务处理 (无法满足依赖关系)
:: 删除 python-crypto 破坏依赖 'python-crypto>=2.6.1' （netease-cloud-music-dl-git 需要）

$ pacman -Si python-crypto
错误：软件包 'python-crypto' 未找到
```

我尝试替换，发现 `ncm` 并不能运行，提示缺少依赖。

```sh
$ ncm
Traceback (most recent call last):
  File "/usr/bin/ncm", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3105, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3089, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3118, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 578, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 895, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 781, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pycrypto>=2.6.1' distribution was not found and is required by netease-cloud-music-dl
```

~~不要跟我讲 pip，全局安装模块时简直就是污染系统目录。~~

最后，麻烦开发者辛苦一下换用 `pycryptodome` 吧。

**Comment by codezjx** [comment]
抱歉，已经更新~   @mengmo @yimiaodaren @chenjunyu19
