### ISSUE TITLE
UnicodeEncodeError: 'gbk' codec can't encode character '\xe5' in position 36: illegal multibyte sequence

### ISSUE THREAD

**Issue by chenyue404** [codezjx/netease-cloud-music-dl#16]
Mp3 file already download: Traceback (most recent call last):
  File "C:\Users\chenyue\AppData\Local\Programs\Python\Python35-32\Scripts\ncm-script.py", line 11, in <module>
    load_entry_point('netease-cloud-music-dl==0.2.0', 'console_scripts', 'ncm')()
  File "C:\Users\chenyue\AppData\Local\Programs\Python\Python35-32\lib\site-packages\netease_cloud_music_dl-0.2.0-py3.5.egg\ncm\start.py", line 76, in main
  File "C:\Users\chenyue\AppData\Local\Programs\Python\Python35-32\lib\site-packages\netease_cloud_music_dl-0.2.0-py3.5.egg\ncm\start.py", line 42, in download_playlist_songs
  File "C:\Users\chenyue\AppData\Local\Programs\Python\Python35-32\lib\site-packages\netease_cloud_music_dl-0.2.0-py3.5.egg\ncm\downloader.py", line 54, in download_song_by_song
UnicodeEncodeError: 'gbk' codec can't encode character '\xe5' in position 36: illegal multibyte sequence

**Comment by codezjx** [comment]
必现的么？还是某首歌才会出现？麻烦提供下歌单或者歌曲ID，谢啦~

**Comment by chenyue404** [comment]
必现的，比如韩文，俄文歌曲。http://music.163.com/#/song?id=5410272

**Comment by codezjx** [comment]
上面的异常是在`print()`打印歌名的时候发生的，然而在Mac下复现不了~  
查了下原因是因为Windows系统的DOS窗口默认用的是gbk编码，在转换非中文字符的时候出错了~
尝试命令行下`chcp 65001`改DOS的编码为utf-8(chcp 936可改回gbk) ，然后右键窗口属性选择`Lucida Console`字体试试~

**Comment by chenyue404** [comment]
谢谢。可以了，改了编码就好了，不用改字体。
