### ISSUE TITLE
Return {'code': -460, 'msg': 'Cheating'} 

### ISSUE THREAD

**Issue by hujy23** [codezjx/netease-cloud-music-dl#26]
无法下载音乐，提示Cheating

```
(venv) hu@NASA:~$ ncm -p http://music.163.com/#/m/playlist?id=438323195
1: Under Construction
Return {'code': -460, 'msg': 'Cheating'} when try to post {'ids': [421563589], 'br': 320000, 'csrf_token': ''} => http://music.163.com/weapi/song/enhance/player/url?csrf_token=
Traceback (most recent call last):
  File "/home/hu/Git/netease-cloud-music-dl/venv/bin/ncm", line 11, in <module>
    load_entry_point('netease-cloud-music-dl==0.2.0', 'console_scripts', 'ncm')()
  File "/home/hu/Git/netease-cloud-music-dl/venv/lib/python3.6/site-packages/netease_cloud_music_dl-0.2.0-py3.6.egg/ncm/start.py", line 76, in main
  File "/home/hu/Git/netease-cloud-music-dl/venv/lib/python3.6/site-packages/netease_cloud_music_dl-0.2.0-py3.6.egg/ncm/start.py", line 42, in download_playlist_songs
  File "/home/hu/Git/netease-cloud-music-dl/venv/lib/python3.6/site-packages/netease_cloud_music_dl-0.2.0-py3.6.egg/ncm/downloader.py", line 49, in download_song_by_song
  File "/home/hu/Git/netease-cloud-music-dl/venv/lib/python3.6/site-packages/netease_cloud_music_dl-0.2.0-py3.6.egg/ncm/api.py", line 73, in get_song_url
```

**Comment by beterhans** [comment]
Same here

hans@VUbuntu:~/source/netease-cloud-music-dl$ ncm -a 2586490
1: The Sign
Return {'code': -460, 'msg': 'Cheating'} when try to post {'ids': [27114570], 'csrf_token': '', 'br': 320000} => http://music.163.com/weapi/song/enhance/player/url?csrf_token=
Traceback (most recent call last):
  File "/usr/local/bin/ncm", line 11, in <module>
    load_entry_point('netease-cloud-music-dl==0.2.0', 'console_scripts', 'ncm')()
  File "/usr/local/lib/python3.5/dist-packages/netease_cloud_music_dl-0.2.0-py3.5.egg/ncm/start.py", line 74, in main
  File "/usr/local/lib/python3.5/dist-packages/netease_cloud_music_dl-0.2.0-py3.5.egg/ncm/start.py", line 33, in download_album_songs
  File "/usr/local/lib/python3.5/dist-packages/netease_cloud_music_dl-0.2.0-py3.5.egg/ncm/downloader.py", line 49, in download_song_by_song
  File "/usr/local/lib/python3.5/dist-packages/netease_cloud_music_dl-0.2.0-py3.5.egg/ncm/api.py", line 73, in get_song_url
TypeError: 'NoneType' object is not subscriptable


网易 更新了？

**Comment by codezjx** [comment]
对的，最近网易君的api接口有更新，做了反爬虫处理。最终发现是对`Cookie`里面的`_ntes_nuid `做了校验，目前采用随机生成`_ntes_nuid `的方式可以解决，参考了以下项目的方案~

https://github.com/Binaryify/NeteaseCloudMusicApi/pull/291

**Comment by hujy23** [comment]
赞 (￣3￣)
