### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by cycleuser** [codezjx/netease-cloud-music-dl#3]
Windows7 X64 anaconda3-4.4.0

```
C:\Users\Administrator\.ncm>ncm -s 123123
Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\ncm-script.py", line 11, in <module>
    load_entry_point('netease-cloud-music-dl==0.2.0', 'console_scripts', 'ncm')(
)
  File "C:\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources
\__init__.py", line 565, in load_entry_point
  File "C:\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources
\__init__.py", line 2598, in load_entry_point
  File "C:\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources
\__init__.py", line 2258, in load
  File "C:\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources
\__init__.py", line 2264, in resolve
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "c:\anaconda3\lib\site-packages\netease_cloud_music_dl-0.2.0-py3.6.egg\nc
m\start.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "c:\anaconda3\lib\site-packages\netease_cloud_music_dl-0.2.0-py3.6.egg\nc
m\config.py", line 13, in <module>
  File "C:\Anaconda3\lib\ntpath.py", line 75, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by codezjx** [comment]
根据log信息，应该是`os.getenv('HOME')`在Windows上返回None的问题。已修复，拉下代码，帮忙测试下~谢啦

**Comment by rahul6612** [comment]
i am getting this error how can i solve this from 4 days i am trying still didn't get solution please any one help me
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not tuple
for more detail visit https://stackoverflow.com/questions/48839305/occured-application-error-in-heroku-with-my-django-app
