### ISSUE TITLE
code': -460, 'msg': 'Cheating'

### ISSUE THREAD

**Issue by 14SHIKE** [codezjx/netease-cloud-music-dl#34]
查到需要在config.py里面添加headers cookie 但不知道怎么做

Return {'code': -460, 'msg': 'Cheating'} when try to post {'ids': [273369], 'br': 320000, 'csrf_token': ''} => http://music.163.com/weapi/song/enhance/player/url?csrf_token=
Traceback (most recent call last):
  File "E:\Python3.6.5\Scripts\ncm-script.py", line 11, in <module>
    load_entry_point('netease-cloud-music-dl==0.2.0', 'console_scripts', 'ncm')()
  File "E:\Python3.6.5\lib\site-packages\netease_cloud_music_dl-0.2.0-py3.6.egg\ncm\start.py", line 76, in main
  File "E:\Python3.6.5\lib\site-packages\netease_cloud_music_dl-0.2.0-py3.6.egg\ncm\start.py", line 42, in download_playlist_songs
  File "E:\Python3.6.5\lib\site-packages\netease_cloud_music_dl-0.2.0-py3.6.egg\ncm\downloader.py", line 49, in download_song_by_song
  File "E:\Python3.6.5\lib\site-packages\netease_cloud_music_dl-0.2.0-py3.6.egg\ncm\api.py", line 73, in get_song_url
TypeError: 'NoneType' object is not subscriptable

**Comment by codezjx** [comment]
请拉下最新的代码，8月份的时候已经修复了~ 参考 #26
