### ISSUE TITLE
大神，Python 3.5 安装报错

### ISSUE THREAD

**Issue by xayangjing** [codezjx/netease-cloud-music-dl#36]
he headers or library files could not be found for zlib,
a required dependency when compiling Pillow from source.

Please see the install instructions at:
   https://pillow.readthedocs.io/en/latest/installation.html

Traceback (most recent call last):
  File "/var/folders/kf/chkwq36d5tjfd8bc4wyxn7cw0000gn/T/easy_install-ml4gskih/Pillow-5.3.0/setup.py", line 802, in <module>
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/john/.virtualenvs/myenv/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 161, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/Users/john/.virtualenvs/myenv/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 147, in call_command
    self.run_command(cmdname)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/john/.virtualenvs/myenv/lib/python3.5/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/build_ext.py", line 338, in run
    self.build_extensions()
  File "/var/folders/kf/chkwq36d5tjfd8bc4wyxn7cw0000gn/T/easy_install-ml4gskih/Pillow-5.3.0/setup.py", line 589, in build_extensions
__main__.RequiredDependencyException: zlib

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/john/.virtualenvs/myenv/lib/python3.5/site-packages/setuptools/sandbox.py", line 157, in save_modules
    yield saved
  File "/Users/john/.virtualenvs/myenv/lib/python3.5/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/Users/john/.virtualenvs/myenv/lib/python3.5/site-packages/setuptools/sandbox.py", line 255, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/Users/john/.virtualenvs/myenv/lib/python3.5/site-packages/setuptools/sandbox.py", line 285, in run
    return func()
  File "/Users/john/.virtualenvs/myenv/lib/python3.5/site-packages/setuptools/sandbox.py", line 253, in runner
    _execfile(setup_script, ns)
  File "/Users/john/.virtualenvs/myenv/lib/python3.5/site-packages/setuptools/sandbox.py", line 47, in _execfile
    exec(code, globals, locals)
  File "/var/folders/kf/chkwq36d5tjfd8bc4wyxn7cw0000gn/T/easy_install-ml4gskih/Pillow-5.3.0/setup.py", line 814, in <module>
__main__.RequiredDependencyException:

The headers or library files could not be found for zlib,
a required dependency when compiling Pillow from source.

Please see the install instructions at:
   https://pillow.readthedocs.io/en/latest/installation.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 26, in <module>
    keywords=['ncm', 'netease', 'cloud-music', 'downloader'],
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/john/.virtualenvs/myenv/lib/python3.5/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/Users/john/.virtualenvs/myenv/lib/python3.5/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/Users/john/.virtualenvs/myenv/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 411, in run
    self.easy_install(spec, not self.no_deps)
  File "/Users/john/.virtualenvs/myenv/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 655, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/Users/john/.virtualenvs/myenv/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 702, in install_item
    self.process_distribution(spec, dist, deps)
  File "/Users/john/.virtualenvs/myenv/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 747, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/Users/john/.virtualenvs/myenv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 851, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/Users/john/.virtualenvs/myenv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1123, in best_match
    return self.obtain(req, installer)
  File "/Users/john/.virtualenvs/myenv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1135, in obtain
    return installer(requirement)
  File "/Users/john/.virtualenvs/myenv/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 674, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/Users/john/.virtualenvs/myenv/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 700, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/Users/john/.virtualenvs/myenv/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 881, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/Users/john/.virtualenvs/myenv/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 1120, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/Users/john/.virtualenvs/myenv/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 1106, in run_setup
    run_setup(setup_script, args)
  File "/Users/john/.virtualenvs/myenv/lib/python3.5/site-packages/setuptools/sandbox.py", line 258, in run_setup
    raise
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/john/.virtualenvs/myenv/lib/python3.5/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/john/.virtualenvs/myenv/lib/python3.5/site-packages/setuptools/sandbox.py", line 169, in save_modules
    saved_exc.resume()
  File "/Users/john/.virtualenvs/myenv/lib/python3.5/site-packages/setuptools/sandbox.py", line 144, in resume
    six.reraise(type, exc, self._tb)
  File "/Users/john/.virtualenvs/myenv/lib/python3.5/site-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/john/.virtualenvs/myenv/lib/python3.5/site-packages/setuptools/sandbox.py", line 157, in save_modules
    yield saved
  File "/Users/john/.virtualenvs/myenv/lib/python3.5/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/Users/john/.virtualenvs/myenv/lib/python3.5/site-packages/setuptools/sandbox.py", line 255, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/Users/john/.virtualenvs/myenv/lib/python3.5/site-packages/setuptools/sandbox.py", line 285, in run
    return func()
  File "/Users/john/.virtualenvs/myenv/lib/python3.5/site-packages/setuptools/sandbox.py", line 253, in runner
    _execfile(setup_script, ns)
  File "/Users/john/.virtualenvs/myenv/lib/python3.5/site-packages/setuptools/sandbox.py", line 47, in _execfile
    exec(code, globals, locals)
  File "/var/folders/kf/chkwq36d5tjfd8bc4wyxn7cw0000gn/T/easy_install-ml4gskih/Pillow-5.3.0/setup.py", line 814, in <module>
setuptools.sandbox.UnpickleableException: RequiredDependencyException('\n\nThe headers or library files could not be found for zlib,\na required dependency when compiling Pillow from source.\n\nPlease see the install instructions at:\n   https://pillow.readthedocs.io/en/latest/installation.html\n\n',)

**Comment by codezjx** [comment]
看了下应该是`Pillow`库依赖的`zlib`没安装导致的，尝试下`pip3 install pillow`。如果还不行就安装个`easy_install`然后执行`easy_install pillow`试下，祝你好运~
