### ISSUE TITLE
AttributeError: parallel

### ISSUE THREAD

**Issue by sushengbuhuo** [codezjx/netease-cloud-music-dl#42]
```js
Installed /usr/lib/python3.4/site-packages/netease_cloud_music_dl-0.2.0-py3.4.egg
Processing dependencies for netease-cloud-music-dl==0.2.0
Searching for Pillow>=4.3.0
Reading http://mirrors.tencentyun.com/pypi/simple/Pillow/
Downloading http://mirrors.tencentyun.com/pypi/packages/81/1a/6b2971adc1bca55b9a53ed1efa372acff7e8b9913982a396f3fa046efaf8/Pillow-6.0.0.tar.gz#md5=9da5d2db0d7604ba553ece1ab7ca53a3
Best match: Pillow 6.0.0
Processing Pillow-6.0.0.tar.gz
Writing /tmp/easy_install-dqt3r9m7/Pillow-6.0.0/setup.cfg
Running Pillow-6.0.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-dqt3r9m7/Pillow-6.0.0/egg-dist-tmp-l45s5_zi
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-dqt3r9m7/Pillow-6.0.0/setup.py", line 792, in <module>
  File "/usr/lib/python3.4/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.4/site-packages/setuptools/command/bdist_egg.py", line 163, in run
    self.run_command("egg_info")
  File "/usr/lib64/python3.4/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.4/site-packages/setuptools/command/egg_info.py", line 296, in run
    self.find_sources()
  File "/usr/lib/python3.4/site-packages/setuptools/command/egg_info.py", line 303, in find_sources
    mm.run()
  File "/usr/lib/python3.4/site-packages/setuptools/command/egg_info.py", line 534, in run
    self.add_defaults()
  File "/usr/lib/python3.4/site-packages/setuptools/command/egg_info.py", line 570, in add_defaults
    sdist.add_defaults(self)
  File "/usr/lib/python3.4/site-packages/setuptools/command/py36compat.py", line 36, in add_defaults
    self._add_defaults_ext()
  File "/usr/lib/python3.4/site-packages/setuptools/command/py36compat.py", line 119, in _add_defaults_ext
    build_ext = self.get_finalized_command('build_ext')
  File "/usr/lib64/python3.4/distutils/cmd.py", line 299, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "/usr/lib64/python3.4/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/tmp/easy_install-dqt3r9m7/Pillow-6.0.0/setup.py", line 268, in finalize_options
  File "/usr/lib64/python3.4/distutils/cmd.py", line 103, in __getattr__
    raise AttributeError(attr)
AttributeError: parallel
```

**Comment by codezjx** [comment]
@sushengbuhuo Try to install `Pillow` by pip3, simple code below:
`pip3 install 'pillow==4.3.0'`
And if the package is already installed and you want to downgrade it add `--force-reinstall` like this:
`pip3 install 'pillow==4.3.0' --force-reinstall`

After installed `Pillow`, try to reinstall `netease-cloud-music-dl`
