### ISSUE TITLE
不太懂报错

### ISSUE THREAD

**Issue by SushenL** [codezjx/netease-cloud-music-dl#46]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/ncm", line 11, in <module>
    load_entry_point('netease-cloud-music-dl==0.2.0', 'console_scripts', 'ncm')()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'ncm'

**Comment by codezjx** [comment]
使用指令`which ncm`查看下可执行文件路径，使用完整路径运行试试~  如果还不行就重新install一下，看着像环境配置的问题。
