### ISSUE TITLE
报错，之前一直正常使用的

### ISSUE THREAD

**Issue by theParkerWong** [codezjx/netease-cloud-music-dl#47]
Traceback (most recent call last):
  File "D:\Python\Scripts\ncm-script.py", line 11, in <module>
    load_entry_point('netease-cloud-music-dl==0.2.0', 'console_scripts', 'ncm')()
  File "D:\Python\lib\site-packages\netease_cloud_music_dl-0.2.0-py3.7.egg\ncm\start.py", line 76, in main
  File "D:\Python\lib\site-packages\netease_cloud_music_dl-0.2.0-py3.7.egg\ncm\start.py", line 42, in download_playlist_songs
  File "D:\Python\lib\site-packages\netease_cloud_music_dl-0.2.0-py3.7.egg\ncm\downloader.py", line 49, in download_song_by_song
  File "D:\Python\lib\site-packages\netease_cloud_music_dl-0.2.0-py3.7.egg\ncm\api.py", line 72, in get_song_url
  File "D:\Python\lib\site-packages\netease_cloud_music_dl-0.2.0-py3.7.egg\ncm\api.py", line 35, in post_request
  File "D:\Python\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "D:\Python\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "D:\Python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by codezjx** [comment]
可以提供一下报错的歌曲id吗？看log应该是解析json的时候某些字段为None导致的

**Comment by theParkerWong** [comment]
不好意思好久之前的事情了，现在不太清楚了。后来下载大部分歌曲都没有问题 👌

**Comment by codezjx** [comment]
好的，有可能服务器抽风，那我先关掉了哈~
