### ISSUE TITLE
AttributeError: type object 'Path' has no attribute 'home'

### ISSUE THREAD

**Issue by kszym2002** [codezjx/netease-cloud-music-dl#5]
# ncm -h
Traceback (most recent call last):
  File "/usr/local/bin/ncm", line 9, in <module>
    load_entry_point('netease-cloud-music-dl==0.2.0', 'console_scripts', 'ncm')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/local/lib/python3.4/dist-packages/netease_cloud_music_dl-0.2.0-py3.4.egg/ncm/start.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/local/lib/python3.4/dist-packages/netease_cloud_music_dl-0.2.0-py3.4.egg/ncm/config.py", line 14, in <module>
AttributeError: type object 'Path' has no attribute 'home'

**Comment by codezjx** [comment]
前两天改代码加了一个python3.5+才支持的系统函数，你的版本是3.4所以报找不到方法。现在用另外一种方式来实现，拉下最新代码，再测试下~先谢啦！

**Comment by EasonSummer** [comment]
謝謝

**Comment by kszym2002** [comment]
謝謝
