### ISSUE TITLE
无法添加封面图片

### ISSUE THREAD

**Issue by chenxiex** [codezjx/netease-cloud-music-dl#66]
错误提示：
```python
Traceback (most recent call last):
  File "/usr/bin/ncm", line 33, in <module>
    sys.exit(load_entry_point('netease-cloud-music-dl==0.2.0', 'console_scripts', 'ncm')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/netease_cloud_music_dl-0.2.0-py3.11.egg/ncm/start.py", line 83, in main
  File "/usr/lib/python3.11/site-packages/netease_cloud_music_dl-0.2.0-py3.11.egg/ncm/downloader.py", line 22, in download_song_by_id
  File "/usr/lib/python3.11/site-packages/netease_cloud_music_dl-0.2.0-py3.11.egg/ncm/downloader.py", line 86, in download_song_by_song
  File "/usr/lib/python3.11/site-packages/netease_cloud_music_dl-0.2.0-py3.11.egg/ncm/file_util.py", line 16, in resize_img
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
```

**Comment by chenxiex** [comment]
原因是pillow 10.0.0更新后，ANTIALIAS被废弃了。
将使用pip将pillow降级至9.5.0即可。
